// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // return android;
        return web;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAcx7emQo8Wvgz9Av46QGrPuTiM6QhgWVE",
      authDomain: "loyality-d5592.firebaseapp.com",
      projectId: "loyality-d5592",
      storageBucket: "loyality-d5592.firebasestorage.app",
      messagingSenderId: "938180858905",
      appId: "1:938180858905:web:adb4aa630a1a3350c70688",
      measurementId: "G-5K7G0PQNK0");

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyCeuHPX8jrLQkziS1uUtU5aM6qm-nkq9Hg',
  //   appId: '1:120762187203:android:50dbef4a01def63ea99176',
  //   messagingSenderId: '120762187203',
  //   projectId: 'flutter-invoice-app',
  //   storageBucket: 'flutter-invoice-app.appspot.com',
  // );
}
